### ISSUE TITLE
Data file for chapter 11 ("colon_s")

### ISSUE THREAD

**Issue by balletmama** [SurgicalInformatics/healthyr_book#20]
Hello, love your book!  I am looking for the "colon_s" data file that is referenced in Chapter 11 (problem with missing data).

Thank you in advance!

-Marne

**Comment by riinuots** [comment]
Thank you!
It comes with the finalfit package, so if you do:
```
library(finalfit)
colon_s <- colon_s
```
it will appear in your environment.

Any other questions let us know!
